type Store {
  uuid: ID!
  city: String
  postalCode: String
  street: String
  street2: String
  street3: String
  addressName: String
  longitude: Float
  latitude: Float
  complexNumber: String
  showWarningMessage: Boolean
  todayOpen: String
  locationType: String
  collectionPoint: Boolean
  sapStoreID: String
  todayClose: String
  distance: Float
}
