# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd frontend
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling Vue App
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: frontend/dist
  files:
    - '**/*'
